/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CompetenciesRouteImport } from './routes/competencies'
import { Route as IgotRouteImport } from './routes/igot'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LearningMaterialsRouteImport } from './routes/learning-materials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as QuizGeneratorRouteImport } from './routes/quiz-generator'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesRoute = CompetenciesRouteImport.update({
  id: '/competencies',
  path: '/competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IgotRoute = IgotRouteImport.update({
  id: '/igot',
  path: '/igot',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningMaterialsRoute = LearningMaterialsRouteImport.update({
  id: '/learning-materials',
  path: '/learning-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGeneratorRoute = QuizGeneratorRouteImport.update({
  id: '/quiz-generator',
  path: '/quiz-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competencies': typeof CompetenciesRoute
  '/igot': typeof IgotRoute
  '/learning': typeof LearningRoute
  '/learning-materials': typeof LearningMaterialsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quiz-generator': typeof QuizGeneratorRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competencies': typeof CompetenciesRoute
  '/igot': typeof IgotRoute
  '/learning': typeof LearningRoute
  '/learning-materials': typeof LearningMaterialsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quiz-generator': typeof QuizGeneratorRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competencies': typeof CompetenciesRoute
  '/igot': typeof IgotRoute
  '/learning': typeof LearningRoute
  '/learning-materials': typeof LearningMaterialsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quiz-generator': typeof QuizGeneratorRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/competencies'
    | '/igot'
    | '/learning'
    | '/learning-materials'
    | '/login'
    | '/notifications'
    | '/quiz-generator'
    | '/recommendations'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/competencies'
    | '/igot'
    | '/learning'
    | '/learning-materials'
    | '/login'
    | '/notifications'
    | '/quiz-generator'
    | '/recommendations'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/competencies'
    | '/igot'
    | '/learning'
    | '/learning-materials'
    | '/login'
    | '/notifications'
    | '/quiz-generator'
    | '/recommendations'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompetenciesRoute: typeof CompetenciesRoute
  IgotRoute: typeof IgotRoute
  LearningRoute: typeof LearningRoute
  LearningMaterialsRoute: typeof LearningMaterialsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  QuizGeneratorRoute: typeof QuizGeneratorRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies': {
      id: '/competencies'
      path: '/competencies'
      fullPath: '/competencies'
      preLoaderRoute: typeof CompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igot': {
      id: '/igot'
      path: '/igot'
      fullPath: '/igot'
      preLoaderRoute: typeof IgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-materials': {
      id: '/learning-materials'
      path: '/learning-materials'
      fullPath: '/learning-materials'
      preLoaderRoute: typeof LearningMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-generator': {
      id: '/quiz-generator'
      path: '/quiz-generator'
      fullPath: '/quiz-generator'
      preLoaderRoute: typeof QuizGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompetenciesRoute: CompetenciesRoute,
  IgotRoute: IgotRoute,
  LearningRoute: LearningRoute,
  LearningMaterialsRoute: LearningMaterialsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  QuizGeneratorRoute: QuizGeneratorRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
